### ISSUE TITLE
Edit languages

### ISSUE THREAD

**Issue by ghost** [TemaSM/LANMP-WDCP-not-maintaining-anymore#1]
How edit lang file for web panel?

**Comment by TemaSM** [comment]
You can fork this repo, edit files in [this directory](https://github.com/TemaSM/LANMP-WDCP/tree/master/CP/v.2.5%20Stable/Source/www/wdlinux/wdcp) and pull your changes into this repo to commit it and bring English lang of WDCP for everyone!

**Comment by wolololo** [comment]
Source files seems encrypted. How?

**Comment by TemaSM** [comment]
I will update it as soon as possible. Sorry for inconvenience. :wink:

**Comment by wolololo** [comment]
Any news?

**Comment by TemaSM** [comment]
No, sorry, don't have a lot of time. You may Fork & play with code :+1: 
P.S> I will close this issue
